//
//  FirstController.H
//  FirstProjects
//
//  Created by White, Nicholas on 1/23/17.
//  Copyright © 2017 CTEC. All rights reserved.
//

#ifndef FirstController_h
#define FirstController_h

class FirstController
{
private:
    void specialOutput();
    int stuffSize;
    void arrayController();
    void buildArray();
public:
    void start();
    void helloWorld();
};

#endif /* FirstController_h */
